data:
  batch_size: 100
  smiles_file: datasets/np_200k.csv
  results_name: results_200k.dat
  encoded_data_file: encoded_data_200k.npy
  data_train_file: data_train_200k.pt
  data_valid_file: data_valid_200k.pt
  encoding_alphabet_file: encoding_alphabet_200k.json

decoder:
  latent_dimension: 50
  gru_neurons_num: 100
  gru_stack_size: 1

encoder:
  layer_1d: 100
  layer_2d: 100
  layer_3d: 100
  latent_dimension: 50

training:
  KLD_alpha: 1.0e-05
  lr_enc: 0.0001
  lr_dec: 0.0001
  num_epochs: 5000
  sample_num: 1000
