data:
  batch_size: 100
  smiles_file: datasets/QM9.csv
  results_name: results_QM9.dat
  encoded_data_file: encoded_data_QM9.npy
  data_train_file: data_train_QM9.pt
  data_valid_file: data_valid_QM9.pt
  encoding_alphabet_file: encoding_alphabet_QM9.json

decoder:
  latent_dimension: 50
  gru_neurons_num: 100
  gru_stack_size: 1

encoder:
  layer_1d: 100
  layer_2d: 100
  layer_3d: 100
  latent_dimension: 50

training:
  KLD_alpha: 1.0e-05
  lr_enc: 0.0001
  lr_dec: 0.0001
  num_epochs: 5000
  sample_num: 1000
